// afung.MangaWeb3.Client.js
(function(){
Type.registerNamespace('afung.MangaWeb3.Client.Modal');afung.MangaWeb3.Client.Modal.ErrorModal=function(){afung.MangaWeb3.Client.Modal.ErrorModal.initializeBase(this,['client','error-modal']);}
afung.MangaWeb3.Client.Modal.ErrorModal.showError=function(errorMsg){if(afung.MangaWeb3.Client.Modal.ErrorModal.$0==null){afung.MangaWeb3.Client.Modal.ErrorModal.$0=new afung.MangaWeb3.Client.Modal.ErrorModal();}afung.MangaWeb3.Client.Modal.ErrorModal.$0.internalShowError(errorMsg);}
afung.MangaWeb3.Client.Modal.ErrorModal.prototype={initialize:function(){},internalShowError:function(errorMsg){$('#error-modal-msg',this.attachedObject).text(errorMsg);this.show();}}
afung.MangaWeb3.Client.Modal.ModalBase=function(template,templateId){this.attachedObject=afung.MangaWeb3.Client.Template.get(template,templateId).appendTo($('body'));this.initialize();}
afung.MangaWeb3.Client.Modal.ModalBase.prototype={attachedObject:null,show:function(){(this.attachedObject).modal();}}
Type.registerNamespace('afung.MangaWeb3.Client');afung.MangaWeb3.Client.ServerType=function(){};afung.MangaWeb3.Client.ServerType.prototype = {aspNet:0,php:1}
afung.MangaWeb3.Client.ServerType.registerEnum('afung.MangaWeb3.Client.ServerType',false);afung.MangaWeb3.Client.Request=function(data,successCallback,failureCallback){this.$0=data;this.$1=successCallback;this.$2=failureCallback;}
afung.MangaWeb3.Client.Request.send=function(data,successCallback,failureCallback){var $0=new afung.MangaWeb3.Client.Request(data,successCallback,failureCallback);$0.$3();}
afung.MangaWeb3.Client.Request.prototype={$0:null,$1:null,$2:null,$3:function(){var $0={};$0.data={j:JSON.stringify(this.$0)};$0.dataType='json';$0.type='POST';$0.cache=false;$0.error=ss.Delegate.create(this,this.$4);$0.success=ss.Delegate.create(this,this.$5);$.ajax(afung.MangaWeb3.Client.Request.endpoint+((!afung.MangaWeb3.Client.Environment.serverType)?'.aspx':'.php'),$0);},$4:function($p0,$p1,$p2){this.$6($p2);},$5:function($p0,$p1,$p2){if(ss.isNullOrUndefined($p0)){return;}var $0=$p0;if(ss.isValue($0.errorCode)||ss.isValue($0.errorMsg)){this.$6(new Error(afung.MangaWeb3.Client.Strings.get($0.errorMsg)));return;}this.$7($p0);},$6:function($p0){if(ss.isValue(this.$2)){this.$2($p0);return;}afung.MangaWeb3.Client.Modal.ErrorModal.showError(String.format(afung.MangaWeb3.Client.Strings.get('RequestFailed'),$p0));},$7:function($p0){if(ss.isValue(this.$1)){this.$1($p0);}}}
afung.MangaWeb3.Client.Application=function(){var $0=function($p1_0){
afung.MangaWeb3.Client.Application.showFatalError(String.format('Unabled to load default language file ({0}). Please check that you have the correct file on your server',$p1_0));};var $1=ss.Delegate.create(this,function(){
var $1_0=ss.Delegate.create(this,function($p2_0){
this.startStage2();});var $1_1=ss.Delegate.create(this,function(){
this.startStage2();});try{afung.MangaWeb3.Client.Strings.loadUserLanguage($1_1,$1_0);}catch($1_2){$1_0($1_2);}});try{afung.MangaWeb3.Client.Strings.loadDefaultLanguage($1,$0);}catch($2){$0($2);}}
afung.MangaWeb3.Client.Application.showFatalError=function(message){var $0=$('<div class="container"><div class="row"><div class="span12"><div class="alert alert-error"><h4>Fatal Error</h4><span class="fatalerrormsg"></span></div></div></div></div>');$('body').prepend($0);$('.fatalerrormsg',$0).text(message);}
afung.MangaWeb3.Client.Application.prototype={startStage2:function(){var $0=function($p1_0){
afung.MangaWeb3.Client.Application.showFatalError($p1_0.toString());};var $1=ss.Delegate.create(this,function(){
this.loadFirstModule();});afung.MangaWeb3.Client.Template.loadTemplateFile($1,$0);},loadFirstModule:function(){}}
afung.MangaWeb3.Client.HtmlConstants=function(){}
afung.MangaWeb3.Client.Strings=function(){}
afung.MangaWeb3.Client.Strings.loadDefaultLanguage=function(successCallback,failureCallback){afung.MangaWeb3.Client.Strings.loadLanguageFile('en-us',successCallback,failureCallback);}
afung.MangaWeb3.Client.Strings.loadUserLanguage=function(successCallback,failureCallback){afung.MangaWeb3.Client.Strings.loadLanguageFile(afung.MangaWeb3.Client.Strings.$1,successCallback,failureCallback);}
afung.MangaWeb3.Client.Strings.loadLanguageFile=function(language,successCallback,failureCallback){if(Object.keyExists(afung.MangaWeb3.Client.Strings.$2,language)){successCallback();return;}var $0=function($p1_0,$p1_1,$p1_2){
failureCallback($p1_2);};var $1=function($p1_0,$p1_1,$p1_2){
afung.MangaWeb3.Client.Strings.$2[language]={};$($p1_0).each(function($p2_0,$p2_1){
var $2_0=$($p2_1);if(!String.compare($p2_1.tagName,'p',true)){var $2_1=$2_0.attr('id');if(!String.isNullOrEmpty($2_1)){afung.MangaWeb3.Client.Strings.$2[language][$2_1]=$2_0.html();}}});successCallback();};var $2={};$2.type='GET';$2.dataType='html';$2.error=$0;$2.success=$1;$.ajax(String.format('lang/{0}.html',language),$2);}
afung.MangaWeb3.Client.Strings.getHtml=function(stringId){if(afung.MangaWeb3.Client.Strings.$1!=='en-us'&&Object.keyExists(afung.MangaWeb3.Client.Strings.$2,afung.MangaWeb3.Client.Strings.$1)&&Object.keyExists(afung.MangaWeb3.Client.Strings.$2[afung.MangaWeb3.Client.Strings.$1],stringId)){return afung.MangaWeb3.Client.Strings.$2[afung.MangaWeb3.Client.Strings.$1][stringId];}else if(Object.keyExists(afung.MangaWeb3.Client.Strings.$2,'en-us')&&Object.keyExists(afung.MangaWeb3.Client.Strings.$2['en-us'],stringId)){return afung.MangaWeb3.Client.Strings.$2['en-us'][stringId];}return 'String Not Defined';}
afung.MangaWeb3.Client.Strings.get=function(stringId){return $('<span>'+afung.MangaWeb3.Client.Strings.getHtml(stringId)+'</span>').text();}
afung.MangaWeb3.Client.Template=function(){}
afung.MangaWeb3.Client.Template.get_$2=function(){if(afung.MangaWeb3.Client.Template.$1==null){afung.MangaWeb3.Client.Template.$1=$(document.createElement('div')).appendTo($('body')).addClass('temp');}return afung.MangaWeb3.Client.Template.$1;}
afung.MangaWeb3.Client.Template.loadTemplateFile=function(successCallback,failureCallback){var $0=0;var $1='';var $2=function(){
};var $3=function($p1_0,$p1_1,$p1_2){
failureCallback(new Error(String.format(afung.MangaWeb3.Client.Strings.get('TemplateLoadError'),$1,$p1_2)));};var $4=function($p1_0,$p1_1,$p1_2){
var $1_0=$(document.createElement('div')).appendTo(afung.MangaWeb3.Client.Template.get_$2()).append($($p1_0));afung.MangaWeb3.Client.Template.$3[$1]={};var $enum1=ss.IEnumerator.getEnumerator(afung.MangaWeb3.Client.Template.templateIds[$1]);while($enum1.moveNext()){var $1_1=$enum1.current;var $1_2=$('#'+$1_1,$1_0);if($1_2.length!==1){failureCallback(new Error(String.format(afung.MangaWeb3.Client.Strings.get('TemplateParseError'),$1,$1_1)));return;}afung.MangaWeb3.Client.Template.$3[$1][$1_1]=$1_2.clone();$1_2.remove();}$1_0.remove();$0++;$2();};$2=function(){
if($0>=afung.MangaWeb3.Client.Template.templates.length){successCallback();return;}$1=afung.MangaWeb3.Client.Template.templates[$0];var $1_0={};$1_0.type='GET';$1_0.dataType='html';$1_0.error=$3;$1_0.success=$4;$.ajax(String.format('template/{0}.html',$1),$1_0);};$2();}
afung.MangaWeb3.Client.Template.get=function(template,templateId){if(Object.keyExists(afung.MangaWeb3.Client.Template.$3,template)&&Object.keyExists(afung.MangaWeb3.Client.Template.$3[template],templateId)){var $0=afung.MangaWeb3.Client.Template.$3[template][templateId];$0=$0.clone().appendTo(afung.MangaWeb3.Client.Template.get_$2());$('.msg',$0).each(function($p1_0,$p1_1){
var $1_0=$($p1_1);var $enum1=ss.IEnumerator.getEnumerator($1_0.attr('class').split(' '));while($enum1.moveNext()){var $1_1=$enum1.current;if($1_1.startsWith('msg-')){$1_0.html(afung.MangaWeb3.Client.Strings.getHtml($1_1.substr(4)));break;}}});$('.plhdr',$0).each(function($p1_0,$p1_1){
var $1_0=$($p1_1);var $enum1=ss.IEnumerator.getEnumerator($1_0.attr('class').split(' '));while($enum1.moveNext()){var $1_1=$enum1.current;if($1_1.startsWith('plhdr-')){$1_0.attr('placeholder',afung.MangaWeb3.Client.Strings.getHtml($1_1.substr(6)));break;}}});return $0.detach();}throw new Error(String.format(afung.MangaWeb3.Client.Strings.get('TemplateGetError'),template,templateId));}
afung.MangaWeb3.Client.Environment=function(){}
Type.registerNamespace('afung.MangaWeb3.Client.Module');afung.MangaWeb3.Client.Module.ModuleBase=function(template,templateId){if(afung.MangaWeb3.Client.Module.ModuleBase.$0!=null){afung.MangaWeb3.Client.Module.ModuleBase.$0.dispose();}afung.MangaWeb3.Client.Module.ModuleBase.$0=null;afung.MangaWeb3.Client.Module.ModuleBase.$0=this;this.attachedObject=afung.MangaWeb3.Client.Template.get(template,templateId).appendTo($('body'));this.initialize();}
afung.MangaWeb3.Client.Module.ModuleBase.prototype={attachedObject:null,dispose:function(){this.attachedObject.remove();}}
afung.MangaWeb3.Client.Modal.ModalBase.registerClass('afung.MangaWeb3.Client.Modal.ModalBase');afung.MangaWeb3.Client.Modal.ErrorModal.registerClass('afung.MangaWeb3.Client.Modal.ErrorModal',afung.MangaWeb3.Client.Modal.ModalBase);afung.MangaWeb3.Client.Request.registerClass('afung.MangaWeb3.Client.Request');afung.MangaWeb3.Client.Application.registerClass('afung.MangaWeb3.Client.Application');afung.MangaWeb3.Client.HtmlConstants.registerClass('afung.MangaWeb3.Client.HtmlConstants');afung.MangaWeb3.Client.Strings.registerClass('afung.MangaWeb3.Client.Strings');afung.MangaWeb3.Client.Template.registerClass('afung.MangaWeb3.Client.Template');afung.MangaWeb3.Client.Environment.registerClass('afung.MangaWeb3.Client.Environment');afung.MangaWeb3.Client.Module.ModuleBase.registerClass('afung.MangaWeb3.Client.Module.ModuleBase',null,ss.IDisposable);afung.MangaWeb3.Client.Modal.ErrorModal.$0=null;afung.MangaWeb3.Client.Request.endpoint='ServerAjax';afung.MangaWeb3.Client.HtmlConstants.attributeChecked='checked';afung.MangaWeb3.Client.HtmlConstants.attributeDisabled='disabled';afung.MangaWeb3.Client.HtmlConstants.attributeId='id';afung.MangaWeb3.Client.HtmlConstants.attributePlaceHolder='placeholder';afung.MangaWeb3.Client.HtmlConstants.classTemp='temp';afung.MangaWeb3.Client.HtmlConstants.tagBody='body';afung.MangaWeb3.Client.HtmlConstants.tagDiv='div';afung.MangaWeb3.Client.HtmlConstants.tagParagraph='p';afung.MangaWeb3.Client.Strings.defaultLanguage='en-us';afung.MangaWeb3.Client.Strings.languages={'en-us':'English (United States)','zh-hk':'Chinese (Hong Kong)'};afung.MangaWeb3.Client.Strings.$1='en-us';afung.MangaWeb3.Client.Strings.$2={};afung.MangaWeb3.Client.Template.templates=['client'];afung.MangaWeb3.Client.Template.templateIds={client:['error-modal']};afung.MangaWeb3.Client.Template.$1=null;afung.MangaWeb3.Client.Template.$3={};afung.MangaWeb3.Client.Environment.serverType=0;afung.MangaWeb3.Client.Module.ModuleBase.$0=null;})();// This script was generated using Script# v0.7.4.0
